### ISSUE TITLE
Search beta blog post

### ISSUE THREAD

**Issue by agjohnson** [rtfd/blog#44]
Once we have search running in production, we should write a blog post. It should:

Tell users about new functionality (eg. all the fancy stuff SimpleQuerySearch does, with example search links)
Tell users how to test it
Ask for feedback and thoughts on improvement
We should aim to have this out by around July 15 or so, so that we have some time to get user feedback before the end of the GSOC.

Moved from https://github.com/rtfd/readthedocs.org/issues/4334

**Comment by safwanrahman** [comment]
@agjohnson This is fixed by #47. Can you close it?
